# Generated by Django 2.2 on 2019-04-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('json', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
