# Generated by Django 2.2 on 2019-04-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='json',
        ),
        migrations.AddField(
            model_name='reporte',
            name='informacion',
            field=models.CharField(default='No hay informacion', max_length=2000000000),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
