# Generated by Django 2.2 on 2019-04-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20190425_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='informacion',
            field=models.CharField(default='No hay informacion', max_length=10485769),
        ),
    ]
