# Generated by Django 2.2 on 2019-04-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_auto_20190425_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='informacion',
            field=models.CharField(default='No hay informacion', max_length=1048575),
        ),
    ]
